version: "3.9"

services:
  bethos:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: bethos-debug
    ports:
      - "3000:3000"
      - "40000:40000"
    environment:
      BENTO_CONFIG: /app/config/pipeline_etl_simulate.yaml
    volumes:
      - .:/app
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
