input:
  kafka_franz:
    seed_brokers:
      - localhost:19091
      - localhost:19092
      - localhost:19093
    topics:
      - sensor-service.dispatch.telemetry-raw
    consumer_group: bento_group

pipeline:
  processors:
    - csv_generator:
        file_path: "./data/telemetry.csv"
        records_per_tick: 1000000

    - csv_reader:
        file_path: "./data/telemetry.csv"
        batch_size: 50000

    - kafka_message_builder: {}

    - uppercase_go: {}

    - telemetry_aggregator:
        resource_map_path: "./config/resource_matrix.json"

output:
  kafka_franz:
    seed_brokers:
      - localhost:19091
      - localhost:19092
      - localhost:19093
    topic: sensor-service.dispatch.telemetry-uppercase
    client_id: bento_processor
